name: Validate Feature Flags

on:
  push:
    paths:
      - 'flags/**/*.json'
      - 'scripts/validate_flags.py'
  pull_request:
    paths:
      - 'flags/**/*.json'
      - 'scripts/validate_flags.py'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install jsonschema

      - name: Run validation
        run: python scripts/validate_flags.py
